pub(crate) mod agg_exec;
pub mod agg_pushdown;
pub mod agg_translator;
pub mod catalog;
pub mod codec;
pub mod document_provider;
pub mod fast_field_reader;
pub mod filter_pushdown;
pub mod full_text_udf;
pub mod index_opener;
pub mod inverted_index_provider;
pub mod ordinal_group_by;
pub(crate) mod plan_traversal;
pub mod schema_mapping;
pub mod single_table_provider;
pub mod table_provider;
pub mod task_estimator;
pub mod topk_pushdown;
pub mod unified_provider;
pub mod warmup;

pub use agg_pushdown::AggPushdown;
pub use agg_translator::{create_session_with_pushdown, execute_aggregations, translate_aggregations};
pub use catalog::{TantivyCatalog, TantivySchema};
pub use codec::{OpenerFactory, OpenerFactoryExt, TantivyCodec};
pub use document_provider::{DocumentDataSource, TantivyDocumentProvider};
pub use filter_pushdown::FastFieldFilterPushdown;
pub use full_text_udf::{extract_full_text_call, full_text_udf};
pub use index_opener::{DirectIndexOpener, IndexOpener, OpenerMetadata};
pub use inverted_index_provider::{InvertedIndexDataSource, TantivyInvertedIndexProvider};
pub use ordinal_group_by::OrdinalGroupByOptimization;
pub use schema_mapping::{tantivy_schema_to_arrow, tantivy_schema_to_arrow_from_index, tantivy_schema_to_arrow_with_multi_valued};
pub use table_provider::{FastFieldDataSource, TantivyTableProvider};
pub use topk_pushdown::TopKPushdown;
pub use single_table_provider::SingleTableProvider;
pub use task_estimator::estimate_task_count;
pub use unified_provider::UnifiedTantivyTableProvider;
